Update template files
hifis-net/ansible-role-rsd pull request #45
Opened 2022-06-21 06:39 UTC by Normo

This PR updates the RSD environment and docker-compose template files by adding missing environment variables.

2022-06-21 07:24 UTC, tobiashuste requested changes
Thanks, @Normo. I added a couple of thoughts also related to the failing CI pipeline.

2022-06-21 07:24 UTC, tobiashuste commented on defaults/main.yml
> +rsd_hgfaai_allow_external_users: "https://login-dev.helmholtz.de/oauth2/token"
This should probably be `true` or `false`?

2022-06-21 07:24 UTC, tobiashuste commented on templates/rsd-secrets.env.j2
> +HELMHOLTZAAI_ALLOW_EXTERNAL_USERS={{ rsd_hgfaai_allow_external_users | bool }}
This might be the reason for the failing CI job?

2022-06-21 07:24 UTC, tobiashuste commented on defaults/main.yml
> +rsd_hgfaai_allow_external_users: "https://login-dev.helmholtz.de/oauth2/token"
The variable is also missing in the README I think.

2022-06-21 10:46 UTC, Normo commented on templates/rsd-secrets.env.j2
> +HELMHOLTZAAI_ALLOW_EXTERNAL_USERS={{ rsd_hgfaai_allow_external_users | bool }}
This should be fixed now.

2022-06-22 08:55 UTC, tobiashuste approved these changes
This looks reasonable now and the pipeline succeeds. Thanks, @Normo :rocket:

2022-06-22 09:13 UTC, merged