Make role ready for production
hifis-net/ansible-role-rsd pull request #50
Opened 2022-06-24 12:23 UTC by Normo

* use container images from [HIFIS fork](https://github.com/hifis-net/RSD-as-a-service) by default
* update variables and README.md
* remove symlink for env file

2022-06-27 13:17 UTC, tobiashuste requested changes
Sorry, one comment ;)

2022-06-27 13:17 UTC, tobiashuste commented on README.md
>    - Default: `changeme`
Shortly after submitting my review I found this and thought, we could also add a 32 character default variable. This way people might read the description more carefully.


```suggestion
  - Default: `changemeChangemeChangemeChangeme`
```

2022-06-27 14:02 UTC, christianhueserhzdr submitted a review, later dismissed
Dear Norman @Normo, I was not able to find any errors, inconsistencies or things to improve. All looks very good. I'll approve this PR.

2022-06-28 10:12 UTC, Normo commented on README.md
>    - Default: `changeme`
I updated it with 2112320683d63366be05b5dfc2243d58128ccb7c

2022-06-28 11:36 UTC, tobiashuste approved these changes
Thanks, @Normo :)

2022-06-28 11:39 UTC, merged